name: MiniMusic
options:
  bundleIdPrefix: com.dhopkins
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    majorVersion: 2.0.0
  MenuBarExtraAccess:
    url: https://github.com/orchetect/MenuBarExtraAccess
    majorVersion: 1.0.0

targets:
  MiniMusic:
    type: application
    platform: macOS
    sources:
      - MiniMusic
    dependencies:
      - package: KeyboardShortcuts
      - package: MenuBarExtraAccess
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boulderhopkins.MiniMusic
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_ENTITLEMENTS: MiniMusic/MiniMusic.entitlements
        GENERATE_INFOPLIST_FILE: true
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: MiniMusic/Info.plist
      properties:
        LSUIElement: true
        NSAppleMusicUsageDescription: "MiniMusic needs access to your Apple Music library to play music and show your playlists."
    entitlements:
      path: MiniMusic/MiniMusic.entitlements
