name: MiniMusic
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: com.dhopkins
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.38"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    majorVersion: 2.0.0
  MenuBarExtraAccess:
    url: https://github.com/orchetect/MenuBarExtraAccess
    majorVersion: 1.0.0

targets:
  MiniMusic:
    type: application
    platform: macOS
    sources:
      - MiniMusic
    dependencies:
      - package: KeyboardShortcuts
      - package: MenuBarExtraAccess
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boulderhopkins.MiniMusic
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
        SWIFT_VERSION: "6.2"
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
        DEVELOPMENT_TEAM: 25RCAA3JLJ
        GENERATE_INFOPLIST_FILE: true
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: Apple Development
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          SWIFT_OPTIMIZATION_LEVEL: -O
          GCC_OPTIMIZATION_LEVEL: s
          SWIFT_COMPILATION_MODE: wholemodule
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          COPY_PHASE_STRIP: true
          STRIP_INSTALLED_PRODUCT: true
    info:
      path: MiniMusic/Info.plist
      properties:
        LSUIElement: true
        NSAppleMusicUsageDescription: "MiniMusic needs access to your Apple Music library to play music and show your playlists."
    entitlements:
      path: MiniMusic/MiniMusic.entitlements
